#!/usr/bin/php
<?php

$Bots = [];
$AllowedFolders = ['.', '..', 'eugene', 'rustamash', 'tgbot4', 'tgbot5'];
		
if ($Handle = opendir('/home')) {
	while (false !== ($Entry = readdir($Handle))) {
		if (!in_array($Entry, $AllowedFolders)) {
			if (preg_match("/(\d)+/u", $Entry, $matches)) {
				$Key = $matches[0];
				$Bots[$Key] = $Entry;
			}
		}
	}
	closedir($Handle);
}

ksort($Bots);

foreach($Bots as $Bot) {
	echo "Removing service {$Bot}...\n";
	exec("systemctl stop {$Bot}");
	usleep(100000);
	exec("systemctl disable {$Bot}");
	usleep(100000);
	exec("rm /etc/systemd/system/{$Bot}.service");
	usleep(100000);
}
exec("systemctl daemon-reload");
usleep(100000);
exec("systemctl reset-failed");

?>
